using System.Reflection;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Formats.Png;

namespace BlazorAtoms.Barcodes.Tests;

/// <summary>
/// Roundtrip check: encode a URL with our own <see cref="QrEncoder"/>, rasterize the module
/// matrix to a PNG via ImageSharp (same pipeline the browser would produce when saving/pasting a
/// QR generated by AtomQrCode), then decode via <c>QrImageDecoder</c>. If this fails, the
/// shipping decoder has a bug against our own generator; if it passes, the decoder is fine and
/// user-reported failures are about specific external images.
/// </summary>
public class QrImageDecoderRoundtripTests
{
    [Theory]
    [InlineData("https://github.com/HowardShank/BlazorAtoms")]
    [InlineData("hello world")]
    [InlineData("HELLO 123 !@#$")]
    public void Encoded_QR_rasterized_to_PNG_decodes_back_to_original(string value)
    {
        var pngBytes = EncodeToPng(value, moduleSize: 24, quietZone: 4);
        var decoded = InvokeDecoder(pngBytes);
        Assert.Equal(value, decoded);
    }

    [Fact]
    public void Small_module_size_still_decodes()
    {
        var pngBytes = EncodeToPng("small", moduleSize: 4, quietZone: 4);
        var decoded = InvokeDecoder(pngBytes);
        Assert.Equal("small", decoded);
    }

    private static byte[] EncodeToPng(string value, int moduleSize, int quietZone)
    {
        var matrix = QrEncoder.Encode(value, QrErrorCorrection.M);
        var n = matrix.GetLength(0);
        var dim = (n + quietZone * 2) * moduleSize;

        using var image = new Image<Rgba32>(dim, dim, new Rgba32(255, 255, 255, 255));
        image.ProcessPixelRows(accessor =>
        {
            for (var r = 0; r < n; r++)
            {
                for (var c = 0; c < n; c++)
                {
                    if (!matrix[r, c]) continue;
                    var y0 = (quietZone + r) * moduleSize;
                    var x0 = (quietZone + c) * moduleSize;
                    for (var dy = 0; dy < moduleSize; dy++)
                    {
                        var row = accessor.GetRowSpan(y0 + dy);
                        for (var dx = 0; dx < moduleSize; dx++)
                            row[x0 + dx] = new Rgba32(0, 0, 0, 255);
                    }
                }
            }
        });

        using var ms = new MemoryStream();
        image.Save(ms, new PngEncoder());
        return ms.ToArray();
    }

    // QrImageDecoder is internal; reflect in.
    private static string? InvokeDecoder(byte[] bytes)
    {
        var t = typeof(BarcodeExportFormat).Assembly.GetType("BlazorAtoms.Barcodes.QrImageDecoder")!;
        var m = t.GetMethod("TryDecode", BindingFlags.Public | BindingFlags.Static)!;
        var result = m.Invoke(null, new object?[] { bytes })!;
        var payloadProp = result.GetType().GetProperty("Payload")!;
        return (string?)payloadProp.GetValue(result);
    }
}
