<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\branding\BlazorAtoms.Branding\BlazorAtoms.Branding.csproj" />
    <ProjectReference Include="..\BlazorWebAppWasmDemo.Client\BlazorWebAppWasmDemo.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

</Project>
