<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BlazorAtoms.BusyIndicators\BlazorAtoms.BusyIndicators.csproj" />
    <ProjectReference Include="..\..\src\BlazorAtoms.Barcodes\BlazorAtoms.Barcodes.csproj" />
  </ItemGroup>

</Project>
